### Import torch library and print version

In [ ]:
import torch
print(torch.__version__)

1.6.0+cu101


### Explore/change Default data type of torch

PyTorch expect to default data type to be **float**. <br>
**PyTorch support total 10 CPU and GPU tensor types.**
https://pytorch.org/docs/stable/tensors.html

In [ ]:
torch.get_default_dtype()

torch.float32

In [ ]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

### Initialize Tensors <br>

*  When we initialize a tensor,default data type will be data type that we set by `set_default_dtype` function



In [ ]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])



*   Specify Tensor Type - we can specify required type when initialize the tensor using `type` function



In [ ]:
tensor_with_type = torch.Tensor([5,3]).type(torch.IntTensor)
tensor_with_type

tensor([5, 3], dtype=torch.int32)



*   `ShortTensor` - Initialize 16bit Int tensors



In [ ]:
tensor_short = torch.ShortTensor([1.0,2.0,3.0]).type(torch.half)
tensor_short

tensor([1., 2., 3.], dtype=torch.float16)



*   `is_tensor` - check for **Tensor** instance 
*   `numel` - get number of elements of a tensor




In [ ]:
print(torch.is_tensor(tensor_arr))
print(torch.numel(tensor_arr))

True
6


#### Uninitialize Tensor
when you specify a Tensor object by given shape without values,PyTorch will allocate the memory for the tensor without intial values



In [ ]:
tensor_uninitialize = torch.Tensor(2,2)
tensor_uninitialize

tensor([[4.1122e-316, 2.1008e-312],
        [9.7612e-313, 2.1432e-312]])

#### Random initialization
Initialize a tensor with random values

In [ ]:
tensor_random = torch.rand(2,2)
tensor_random

tensor([[0.4450, 0.9153],
        [0.4897, 0.1905]])

#### Initialize Tensor with a specific value


*   `torch.full` - create tensor for given shape with `fill_value` argument



In [ ]:
tensor_fill = torch.full((2,6),fill_value=10,dtype=torch.float32)
tensor_fill

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]], dtype=torch.float32)



*   `torch.ones` - create tensor with value 1
*   `torch.zeros` - create tensor with value 0







In [ ]:
tensor_ones = torch.ones(size=(2,4))
tensor_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
tensor_zeros = torch.zeros(size=(5,5))
tensor_zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])



*   `torch.zeros_like` - Initialize zeros tensor with same shape of an another tensor
*   `torch.ones_like` - Initialize ones tensor with same shape of an another tensor



In [ ]:
zeros_like_of_ones_shape = torch.zeros_like(tensor_ones)
zeros_like_of_ones_shape

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones_like_of_zeros_shape = torch.ones_like(tensor_zeros)
ones_like_of_zeros_shape

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])



*   `torch.eye` - tensor with ones on the diagonal and zeros elsewhere



In [ ]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])



*   `torch.nonzero` - find non zero indicies of a given tensor



In [ ]:
non_zero = torch.nonzero(tensor_eye,as_tuple=False)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])



*   sparse tensor



### Simple Tensor Operations

In [ ]:
init_tensor = torch.rand(2,3)
init_tensor

tensor([[0.1584, 0.7537, 0.9658],
        [0.3346, 0.5583, 0.7014]])



*   Operations that modify the tensor in-place have an "_" suffix 

