### Contents


1.   [Initialize Tensors](#initialize_tensors)
2.   [Simple Tensor Operations](#tensor_operations)
3.   [Basic Elementwise and Matrix Operations](#tensor_operations)
4.   [Conversion between PyTorch and Numpy](#tensor_operations)



### Import torch library and print version

In [ ]:
import torch
print(torch.__version__)

1.6.0+cu101


### Explore/change Default data type of torch

PyTorch expect to default data type to be **float**. <br>
**PyTorch support total 10 CPU and GPU tensor types.**
https://pytorch.org/docs/stable/tensors.html

In [ ]:
torch.get_default_dtype()

torch.float32

In [ ]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

<a id="initialize_tensors"></a>
### Initialize Tensors <br>

*  When we initialize a tensor,default data type will be data type that we set by `set_default_dtype` function



In [ ]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])



*   Specify Tensor Type - we can specify required type when initialize the tensor using `type` function



In [ ]:
tensor_with_type = torch.Tensor([5,3]).type(torch.IntTensor)
tensor_with_type

tensor([5, 3], dtype=torch.int32)



*   `ShortTensor` - Initialize 16bit Int tensors



In [ ]:
tensor_short = torch.ShortTensor([1.0,2.0,3.0]).type(torch.half)
tensor_short

tensor([1., 2., 3.], dtype=torch.float16)



*   `is_tensor` - check for **Tensor** instance 
*   `numel` - get number of elements of a tensor




In [ ]:
print(torch.is_tensor(tensor_arr))
print(torch.numel(tensor_arr))

True
6


#### Uninitialize Tensor
when you specify a Tensor object by given shape without values,PyTorch will allocate the memory for the tensor without intial values



In [ ]:
tensor_uninitialize = torch.Tensor(2,2)
tensor_uninitialize

tensor([[4.1122e-316, 2.1008e-312],
        [9.7612e-313, 2.1432e-312]])

#### Random initialization
Initialize a tensor with random values

In [ ]:
tensor_random = torch.rand(2,2)
tensor_random

tensor([[0.4450, 0.9153],
        [0.4897, 0.1905]])

#### Initialize Tensor with a specific value


*   `torch.full` - create tensor for given shape with `fill_value` argument



In [ ]:
tensor_fill = torch.full((2,6),fill_value=10,dtype=torch.float32)
tensor_fill

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]], dtype=torch.float32)



*   `torch.ones` - create tensor with value 1
*   `torch.zeros` - create tensor with value 0







In [ ]:
tensor_ones = torch.ones(size=(2,4))
tensor_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
tensor_zeros = torch.zeros(size=(5,5))
tensor_zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])



*   `torch.zeros_like` - Initialize zeros tensor with same shape of an another tensor
*   `torch.ones_like` - Initialize ones tensor with same shape of an another tensor



In [ ]:
zeros_like_of_ones_shape = torch.zeros_like(tensor_ones)
zeros_like_of_ones_shape

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones_like_of_zeros_shape = torch.ones_like(tensor_zeros)
ones_like_of_zeros_shape

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])



*   `torch.eye` - tensor with ones on the diagonal and zeros elsewhere



In [ ]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])



*   `torch.nonzero` - find non zero indicies of a given tensor



In [ ]:
non_zero = torch.nonzero(tensor_eye,as_tuple=False)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])



*   sparse tensor



<a id="tensor_operations"></a>
### Simple Tensor Operations

In [ ]:
init_tensor = torch.rand(2,3)
init_tensor

tensor([[0.3179, 0.9527, 0.8980],
        [0.3197, 0.8681, 0.0358]])

#### Inplace Operations
Operations that modify the tensor in-place have an "_" suffix and other functions make a copy of modified items.


*  ` fill_` function fill tensor with given value inplace
*   `add_` function add given value to all elements in the tensor in place
*   `sqrt_` function calculate square root of all elements in place







In [ ]:
init_tensor.fill_(10)
init_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [ ]:
init_tensor.add_(5)
init_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [ ]:
init_tensor.sqrt_()
init_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

#### Generate/split/concatenation

*   `linespace` function generate evenly spaced numbers in given range
*   `chunk` function chunk tensor to a given number of parts
* `cat` function concatenate tensors in a given dimention


In [ ]:
x = torch.linspace(start=0.1,end=10.0,steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [ ]:
tensor_chunks = torch.chunk(x,3,0)
tensor_chunks

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [ ]:
tensor_1 = tensor_chunks[0]
tensor_2 = tensor_chunks[1]
tensor_3 = tensor_chunks[2]

tensor_concat = torch.cat((tensor_1,tensor_2,tensor_3),0)
tensor_concat

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

#### Size/Shape/View


*   `size` function returns size of the tensor along each dimention
*   `shape` attribute returns shape of the tensor 

*   `view` function returns view of a tensor in a given different shape



In [ ]:
random_tensor = torch.Tensor([[10,8,2],[40,5,6],[13,11,3]])
random_tensor

tensor([[10.,  8.,  2.],
        [40.,  5.,  6.],
        [13., 11.,  3.]])

In [ ]:
random_tensor.size()

torch.Size([3, 3])

In [ ]:
random_tensor.shape

torch.Size([3, 3])

In [ ]:
resized_tensor = random_tensor.view(9)
resized_tensor

tensor([10.,  8.,  2., 40.,  5.,  6., 13., 11.,  3.])

#### Access/Modify tensor values


*   We can access tensor values using indexs or array slicing
*   We can modify tensor values by accessing indexes and assign new values to it



In [ ]:
# get value of 1st row 3rd column
print(random_tensor[0,2])

# get value of 2nd row 2nd column
print(random_tensor[1,1])

tensor(2.)
tensor(5.)


In [ ]:
# get all value from 2nd row and 2nd column
print(random_tensor[1:,1:])

tensor([[ 5.,  6.],
        [11.,  3.]])


In [ ]:
random_tensor[2,2] = 100
random_tensor

tensor([[ 10.,   8.,   2.],
        [ 40.,   5.,   6.],
        [ 13.,  11., 100.]])

In [ ]:
random_tensor[1,1]=500
random_tensor

tensor([[ 10.,   8.,   2.],
        [ 40., 500.,   6.],
        [ 13.,  11., 100.]])

#### Squeeze/Unsqueeze and Transpose


*   `unsqueeze` function returns a new tensor with a dimension of size one inserted at the specified position
*   `squeeze` function returns a tensor with all the dimensions of input of size 1 removed.
* `transpose` returns transposed version of tensor


In [ ]:
print("Before shape ",random_tensor.shape)
tensor_unsqueeze = torch.unsqueeze(random_tensor,2)
print("After shape ",tensor_unsqueeze.shape)

Before shape  torch.Size([3, 3])
After shape  torch.Size([3, 3, 1])


In [ ]:
print("Before shape ",tensor_unsqueeze.shape)
tensor_squeeze = torch.squeeze(tensor_unsqueeze)
print("After shape ",tensor_squeeze.shape)

Before shape  torch.Size([3, 3, 1])
After shape  torch.Size([3, 3])


In [ ]:
tensor_transposed = torch.transpose(random_tensor,0,1)
tensor_transposed

tensor([[ 10.,  40.,  13.],
        [  8., 500.,  11.],
        [  2.,   6., 100.]])

In [ ]:
random_tensor

tensor([[ 10.,   8.,   2.],
        [ 40., 500.,   6.],
        [ 13.,  11., 100.]])

### Elementwise and Matrix Operations



*   `sort` function sort tensor and indicies in a given axis
*   `abs` function create absolute values of a given tensor
* `clamp` clamp all elements in to range of min and max
* `argmax` function retuends indicies of largest element in a given dimention
* `argmin` function returns indicies of  smallest element in a given dimention





In [ ]:
random_tensor = torch.Tensor([[10,8,2],[40,5,6],[13,11,3]])

In [ ]:
sorted_tensor,sorted_indicies = torch.sort(random_tensor)
print(sorted_tensor)
print(sorted_indicies)

tensor([[ 2.,  8., 10.],
        [ 5.,  6., 40.],
        [ 3., 11., 13.]])
tensor([[2, 1, 0],
        [1, 2, 0],
        [2, 1, 0]])


In [ ]:
tensor_float = torch.FloatTensor([-2.42,-3.5,10,11.2])
tensor_float

tensor([-2.4200, -3.5000, 10.0000, 11.2000])

In [ ]:
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([ 2.4200,  3.5000, 10.0000, 11.2000])

In [ ]:
clamp_tensor = torch.clamp(random_tensor,min=3,max=10)
clamp_tensor

tensor([[10.,  8.,  3.],
        [10.,  5.,  6.],
        [10., 10.,  3.]])

#### basic mathematical operations

*   `add` function or ` +` for elementwise addition
*   `div` function or `/` for elementwise division
* `mul` or `*` for elementwise multipication
* `sub` or `-` for elementwise substraction



In [ ]:
tensor_1 = torch.randn(2,3)
tensor_2 = torch.randn(2,3)

In [ ]:
add1 = tensor_1+tensor_2
add1

tensor([[ 0.5891, -0.6282,  0.2012],
        [ 1.7793,  0.8440, -2.2393]])

In [ ]:
add2 = torch.add(tensor_1,tensor_2)
add2

tensor([[ 0.5891, -0.6282,  0.2012],
        [ 1.7793,  0.8440, -2.2393]])

In [ ]:
tensor_3 = torch.randn(2,3)
tensor_3

tensor([[-0.3547, -0.3156,  1.6132],
        [ 0.2720, -0.5786, -0.9567]])

In [ ]:
div1 = tensor_1 / tensor_3
div1

tensor([[ 0.5257,  2.6509, -0.1255],
        [ 3.5270, -0.8841,  1.8236]])

In [ ]:
div2 = torch.div(tensor_1,tensor_3)
div2

tensor([[ 0.5257,  2.6509, -0.1255],
        [ 3.5270, -0.8841,  1.8236]])

In [ ]:
mul1 = tensor_1*tensor_2
mul1

tensor([[-0.1446, -0.1742, -0.0817],
        [ 0.7866,  0.1700,  0.8632]])

In [ ]:
mul2 = torch.mul(tensor_1,tensor_2)
mul2

tensor([[-0.1446, -0.1742, -0.0817],
        [ 0.7866,  0.1700,  0.8632]])

In [ ]:
sub1 = tensor_1 - tensor_2
sub1

tensor([[-0.9620, -1.0448, -0.6061],
        [ 0.1396,  0.1792, -1.2498]])

In [ ]:
sub2 = torch.sub(tensor_1,tensor_2)
sub2

tensor([[-1.1651, -3.0757, -2.3863],
        [-0.6818, -0.2458,  1.3192]])

In [ ]:
#largest value indicies in row wise (dim=1)
argmax = torch.argmax(sub2,dim=1)
print("Largest value indicies row wise",argmax)

argmax = torch.argmax(sub2,dim=0)
print("Largest value indicies column wise",argmax)

Largest value indicies row wise tensor([0, 2])
Largest value indicies column wise tensor([1, 1, 1])


In [ ]:
#largest value indicies in row wise (dim=1)
argmin = torch.argmin(sub2,dim=1)
print("Smallest value indicies row wise",argmin)

argmin = torch.argmax(sub2,dim=0)
print("Smallest value indicies column wise",argmin)

Smallest value indicies row wise tensor([1, 0])
Smallest value indicies column wise tensor([1, 1, 1])


#### Basic matrix operations


*   `dot` function perform  dot product
*   `mv` function multiply matrix by the corresponding vector
* `mm` function multiply matrix by matrix



In [ ]:
t1 = torch.Tensor([1,2])
t2 = torch.Tensor([10,20])

In [ ]:
dot_product = torch.dot(t1,t2)
dot_product

tensor(50.)

In [ ]:
matrix = torch.Tensor([[1,2,3],
                       [4,5,6]])
vector = torch.Tensor([0,1,2])

In [ ]:
matrix_vector = torch.mv(matrix,vector)
matrix_vector

tensor([ 8., 17.])

In [ ]:
matrix_one = torch.Tensor([[1,2,3],
                           [4,5,6]])
matrix_two = torch.Tensor([[10,20],
                           [30,40],
                           [50,60]])

In [ ]:
matrix_mul = torch.mm(matrix_one,matrix_two)
matrix_mul

tensor([[220., 280.],
        [490., 640.]])

### Conversion between PyTorch and Numpy


*   `numpy` function convert torch Tensor to numpy array
*   `from_numpy` function returns a torch Tensor from numpy array

**But both numpy array and torch Tensor share the same underline memory.If we update numpy array,it will update torch Tensor as well.**




In [ ]:
import numpy as np

In [ ]:
tensor = torch.rand(4,3)
print(type(tensor))

<class 'torch.Tensor'>




*   convert torch Tensor to numpy



In [ ]:
numpy_from_torch = tensor.numpy()
print(type(numpy_from_torch))

<class 'numpy.ndarray'>


In [ ]:
print(torch.is_tensor(tensor))
print(torch.is_tensor(numpy_from_torch))

True
False




*    changing values of a one instance will effect to both numpy and torch Tensor



In [ ]:
numpy_from_torch

array([[0.66118073, 0.64069164, 0.90291804],
       [0.3827008 , 0.98659307, 0.6486511 ],
       [0.99074495, 0.18981278, 0.967396  ],
       [0.10482919, 0.18436086, 0.8443978 ]], dtype=float32)

In [ ]:
numpy_from_torch[0,0] = 100

In [ ]:
numpy_from_torch

array([[100.        ,   0.64069164,   0.90291804],
       [  0.3827008 ,   0.98659307,   0.6486511 ],
       [  0.99074495,   0.18981278,   0.967396  ],
       [  0.10482919,   0.18436086,   0.8443978 ]], dtype=float32)

In [ ]:
tensor

tensor([[100.0000,   0.6407,   0.9029],
        [  0.3827,   0.9866,   0.6487],
        [  0.9907,   0.1898,   0.9674],
        [  0.1048,   0.1844,   0.8444]])



* Create torch Tensor from numpy array



In [ ]:
np_array = np.array([[1,2,3],
                     [4,5,6],
                     [6,7,8]])
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
tensor_from_numpy = torch.from_numpy(np_array)
tensor_from_numpy

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

In [ ]:
torch.is_tensor(tensor_from_numpy)

True

In [ ]:
tensor_from_numpy[1,1] = 500

In [ ]:
tensor_from_numpy

tensor([[  1,   2,   3],
        [  4, 500,   6],
        [  6,   7,   8]])

In [ ]:
np_array

array([[  1,   2,   3],
       [  4, 500,   6],
       [  6,   7,   8]])